spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: pas1234

server:
  port: 8080